# Ansible Galaxy collection requirements for ansible-git-catc
# Compatible with Cisco Catalyst Center version 2.3.7.9

collections:
  - name: cisco.dnac
    version: "6.33.2"
  - name: community.general
