---
- name: Template Synchronization from Git using Template Workflow Manager
  hosts: catalyst_center
  gather_facts: yes
  vars_files:
    - vault.yml
  vars:
    DEBUG: "{{ lookup('env', 'DEBUG') | default(false) | bool }}"

  module_defaults:
    cisco.dnac.template_workflow_manager:
      dnac_host: "{{ dnac_host }}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"
      dnac_version: "{{ dnac_version }}"
      dnac_debug: "{{ dnac_debug }}"
      dnac_log_level: "{{ dnac_log_level }}"
      dnac_log: "{{ dnac_log }}"

  tasks:
    - name: Set execution timestamp
      set_fact:
        start_timestamp: "{{ ansible_date_time }}"

    - name: --DEBUG-- Execution timestamp
      when: DEBUG
      debug:
        msg: "{{ start_timestamp.date + ' ' + start_timestamp.time }}"

    - name: Clone templates project from GitHub repo
      ansible.builtin.git:
        accept_hostkey: yes
        repo: "{{ git_repo }}"
        dest: "{{ git_local_dest }}"
        version: "{{ git_branch | default('HEAD') }}"
        update: yes
        force: yes
      register: git_clone_result

    - name: Get cloned template list
      find:
        paths: "{{ git_local_dest }}"
        patterns: "*.{{ template_extension }}"
        recurse: yes
        file_type: file
      register: template_file_list

    - name: Get Project name from template folder
      set_fact:
        projectName: "{{ template_file_list.files[0].path | dirname | basename }}"

    - name: --DEBUG-- Project Name
      when: DEBUG
      debug:
        msg: "{{ projectName }}"

    - name: Get template commit messages
      ansible.builtin.shell:
        cmd: "git log --pretty=format:\"%ad | %B [%an]\" -1 --date=short -- '{{ item.path }}'"
        chdir: "{{ item.path | dirname }}"
      with_items: "{{ template_file_list.files }}"
      register: template_git_log
      changed_when: false

    - name: Get template diff log
      ansible.builtin.shell:
        cmd: "git log --pretty=format:\"%H\" -p -1 --date=short -- '{{ item.path }}'"
        chdir: "{{ item.path | dirname }}"
      with_items: "{{ template_file_list.files }}"
      register: template_git_diff
      changed_when: false

    # CRITICAL: Template Processing Order
    # Catalyst Center requires templates to be created in a specific order to avoid dependency errors.
    # 
    # Definition Templates (DEFN-*):
    #   These templates define data structures and are included by FABRIC-* templates.
    #   They must be created first in this order:
    #   1. DEFN-MCAST: Multicast definitions for EVPN fabric
    #   2. DEFN-VRF: VRF definitions for multi-tenancy (red, blue, green)
    #   3. DEFN-ROLES: Device role definitions (spine/leaf/border nodes)
    #   4. DEFN-LOOPBACKS: Loopback interface definitions for underlay/overlay
    #   5. DEFN-VNIOFFSETS: VNI offset definitions for L2 and L3 VNIs
    #   6. DEFN-OVERLAY: Overlay network definitions with VLANs and SVIs
    #   7. DEFN-L3OUT: Layer 3 external connectivity definitions
    #   8. DEFN-NAC-IOT: NAC IoT definitions
    #   9. DEFN-IPSEC: IPSec tunnel definitions for multi-cluster
    #
    # Function Templates (FUNC-*):
    #   10. FUNC-OBJECT-MACROS: Jinja2 macros for VRF object resolution
    #
    # Fabric Templates (FABRIC-*):
    #   These templates generate device configurations and must be created after DEFN-* templates:
    #   11. FABRIC-VRF: VRF configuration for multi-tenancy
    #   12. FABRIC-LOOPBACKS: Loopback interface configuration
    #   13. FABRIC-NVE: Network Virtualization Edge (NVE) interface configuration
    #   14. FABRIC-MCAST: Multicast configuration for BUM traffic
    #   15. FABRIC-EVPN: BGP EVPN control plane configuration
    #   16. FABRIC-OVERLAY: VXLAN overlay network services
    #   17. FABRIC-IPSEC: IPSec tunnel configuration
    #   18. FABRIC-NAC-IOT: Network Access Control for IoT
    #   19. FABRIC-L3OUT: Layer 3 external connectivity configuration
    #
    # Composite Template:
    #   BGP-EVPN-BUILD: Combines FABRIC-* templates in the correct order (created after all individual templates)
    
    - name: Define template processing order
      set_fact:
        template_order:
          DEFN-MCAST.j2: 1
          DEFN-VRF.j2: 2
          DEFN-ROLES.j2: 3
          DEFN-LOOPBACKS.j2: 4
          DEFN-VNIOFFSETS.j2: 5
          DEFN-OVERLAY.j2: 6
          DEFN-L3OUT.j2: 7
          DEFN-NAC-IOT.j2: 8
          DEFN-IPSEC.j2: 9
          FUNC-OBJECT-MACROS.j2: 10
          FABRIC-VRF.j2: 11
          FABRIC-LOOPBACKS.j2: 12
          FABRIC-NVE.j2: 13
          FABRIC-MCAST.j2: 14
          FABRIC-EVPN.j2: 15
          FABRIC-OVERLAY.j2: 16
          FABRIC-IPSEC.j2: 17
          FABRIC-NAC-IOT.j2: 18
          FABRIC-L3OUT.j2: 19

    - name: Initialize templates with sort keys
      set_fact:
        templates_with_keys: []

    - name: Add sort key to each template file
      set_fact:
        templates_with_keys: "{{ templates_with_keys + [item | combine({'sort_key': template_order[item.path | basename] | default(9999)})] }}"
      loop: "{{ template_file_list.files }}"

    - name: Sort templates by defined order
      set_fact:
        sorted_template_files: "{{ templates_with_keys | sort(attribute='sort_key') }}"

    - name: --DEBUG-- show sorted template list
      when: DEBUG
      debug:
        msg: "{{ sorted_template_files | map(attribute='path') | map('basename') | list }}"

    - name: Process regular templates in correct order
      include_tasks: process-template.yml
      with_items: "{{ sorted_template_files }}"
      loop_control:
        loop_var: template_file
        index_var: template_idx

    - name: --DEBUG-- show template configurations
      when: DEBUG
      debug:
        msg: "{{ template_workflow_configs }}"

    - name: Find composite definition YAML files in synced repo
      find:
        paths: "{{ git_local_dest }}"
        patterns: "*.yml"
        file_type: file
        recurse: yes
      register: composite_definition_files

    - name: Process composite templates
      when: composite_definition_files.files | length > 0
      include_tasks: process-composite.yml
      with_items: "{{ composite_definition_files.files }}"
      loop_control:
        loop_var: composite_file

    - name: --DEBUG-- show composite configurations
      when: DEBUG and composite_workflow_configs is defined
      debug:
        msg: "{{ composite_workflow_configs }}"

    - name: Synchronize all templates using template_workflow_manager
      when: template_workflow_configs is defined
      cisco.dnac.template_workflow_manager:
        state: merged
        config: "{{ template_workflow_configs }}"
      register: template_sync_result

    - name: --DEBUG-- show template sync results
      when: DEBUG
      debug:
        msg: "{{ template_sync_result }}"

    - name: Synchronize composite templates using template_workflow_manager
      when: composite_workflow_configs is defined
      cisco.dnac.template_workflow_manager:
        state: merged
        config: "{{ composite_workflow_configs }}"
      register: composite_sync_result

    - name: --DEBUG-- show composite sync results
      when: DEBUG and composite_sync_result is defined
      debug:
        msg: "{{ composite_sync_result }}"

    - name: Display synchronization summary
      debug:
        msg:
          - "Template synchronization completed successfully"
          - "Project: {{ projectName }}"
          - "Regular templates synced: {{ template_workflow_configs | default([]) | length }}"
          - "Composite templates synced: {{ composite_workflow_configs | default([]) | length }}"
          - "Timestamp: {{ start_timestamp.date + ' ' + start_timestamp.time }}"
