# ============================================================================
# Authors
# ============================================================================
# | Name            | Role                              | Contact              |
# |-----------------|-----------------------------------|----------------------|
# | Igor Manassypov | Systems Engineer                  | imanassy@cisco.com   |
# | Keith Baldwin   | Technical Solutions Architect     | kebaldwi@cisco.com   |
# | Pawan Singh     | Engineering Technical Leader      | pawansi@cisco.com    |
#
# Copyright © 2024-2026 Cisco Systems, Inc. All rights reserved.
# ============================================================================

---
- name: Template Synchronization from Git using Template Workflow Manager
  hosts: catalyst_center
  gather_facts: yes
  vars_files:
    - vault.yml
  vars:
    DEBUG: "{{ lookup('env', 'DEBUG') | default(false) | bool }}"

  module_defaults:
    cisco.dnac.template_workflow_manager:
      dnac_host: "{{ dnac_host }}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"
      dnac_version: "{{ dnac_version }}"
      dnac_debug: "{{ dnac_debug }}"
      dnac_log_level: "{{ dnac_log_level }}"
      dnac_log: "{{ dnac_log }}"

  tasks:
    - name: Set execution timestamp
      set_fact:
        start_timestamp: "{{ ansible_date_time }}"

    - name: --DEBUG-- Execution timestamp
      when: DEBUG
      debug:
        msg: "{{ start_timestamp.date + ' ' + start_timestamp.time }}"

    - name: Clone templates project from GitHub repo
      ansible.builtin.git:
        accept_hostkey: yes
        repo: "{{ git_repo }}"
        dest: "{{ git_local_dest }}"
        version: "{{ git_branch | default('HEAD') }}"
        update: yes
        force: yes
      register: git_clone_result

    - name: Get cloned template list
      find:
        paths: "{{ git_local_dest }}"
        patterns: "*.{{ template_extension }}"
        recurse: yes
        file_type: file
      register: template_file_list

    - name: Get Project name from template folder
      set_fact:
        projectName: "{{ projectName | default(template_file_list.files[0].path | dirname | basename) }}"

    - name: --DEBUG-- Project Name
      when: DEBUG
      debug:
        msg: "{{ projectName }}"

    - name: Get template commit messages
      ansible.builtin.shell:
        cmd: "git log --pretty=format:\"%ad | %B [%an]\" -1 --date=short -- '{{ item.path }}'"
        chdir: "{{ item.path | dirname }}"
      with_items: "{{ template_file_list.files }}"
      register: template_git_log
      changed_when: false

    - name: Get template diff log
      ansible.builtin.shell:
        cmd: "git log --pretty=format:\"%H\" -p -1 --date=short -- '{{ item.path }}'"
        chdir: "{{ item.path | dirname }}"
      with_items: "{{ template_file_list.files }}"
      register: template_git_diff
      changed_when: false

    # DYNAMIC TEMPLATE PROCESSING ORDER
    # Instead of a static template_order dictionary, the playbook dynamically determines
    # template processing order based on composite template definitions:
    # 
    # 1. Find all composite definition YAML files (.yml) in the repository
    # 2. Extract templates referenced in those composites (these are dependencies)
    # 3. Process priority templates first (templates referenced in composites)
    # 4. Process regular templates second (templates not referenced in composites)
    # 5. Process composite templates last (after all dependencies exist in Catalyst Center)
    #
    # This approach ensures templates are created in the correct dependency order without
    # maintaining a hard-coded list, making the playbook more flexible and maintainable.

    - name: Find composite definition YAML files in synced repo
      find:
        paths: "{{ git_local_dest }}"
        patterns: "*.yml"
        file_type: file
        recurse: yes
      register: composite_definition_files

    - name: Extract templates referenced in composite definitions
      set_fact:
        composite_referenced_templates: "{{ composite_referenced_templates | default([]) + (lookup('file', item.path) | from_yaml).templates | map(attribute='name') | list }}"
      with_items: "{{ composite_definition_files.files }}"
      when: composite_definition_files.files | length > 0

    - name: --DEBUG-- Templates referenced in composites
      when: DEBUG and composite_referenced_templates is defined
      debug:
        msg: "{{ composite_referenced_templates }}"

    - name: Separate templates into priority and regular lists
      set_fact:
        priority_template_list: []
        regular_template_list: []

    - name: Build template lists based on composite references
      set_fact:
        priority_template_list: "{{ priority_template_list + [item] if (composite_referenced_templates is defined and item.path | basename in composite_referenced_templates) else priority_template_list }}"
        regular_template_list: "{{ regular_template_list + [item] if (composite_referenced_templates is not defined or item.path | basename not in composite_referenced_templates) else regular_template_list }}"
      loop: "{{ template_file_list.files }}"

    - name: Set template processing order (regular first for dependencies, then priority)
      set_fact:
        sorted_template_files: "{{ regular_template_list + priority_template_list }}"

    - name: --DEBUG-- show sorted template list
      when: DEBUG
      debug:
        msg: "{{ sorted_template_files | map(attribute='path') | map('basename') | list }}"

    - name: Process regular templates in correct order
      include_tasks: process-template.yml
      with_items: "{{ sorted_template_files }}"
      loop_control:
        loop_var: template_file
        index_var: template_idx

    - name: --DEBUG-- show template configurations
      when: DEBUG
      debug:
        msg: "{{ template_workflow_configs }}"

    - name: Process composite templates
      when: composite_definition_files.files | length > 0
      include_tasks: process-composite.yml
      with_items: "{{ composite_definition_files.files }}"
      loop_control:
        loop_var: composite_file

    - name: --DEBUG-- show composite configurations
      when: DEBUG and composite_workflow_configs is defined
      debug:
        msg: "{{ composite_workflow_configs }}"

    - name: Synchronize all templates using template_workflow_manager
      when: template_workflow_configs is defined
      cisco.dnac.template_workflow_manager:
        state: merged
        config: "{{ template_workflow_configs }}"
      register: template_sync_result

    - name: --DEBUG-- show template sync results
      when: DEBUG
      debug:
        msg: "{{ template_sync_result }}"

    - name: Synchronize composite templates using template_workflow_manager
      when: composite_workflow_configs is defined
      cisco.dnac.template_workflow_manager:
        state: merged
        config: "{{ composite_workflow_configs }}"
      register: composite_sync_result

    - name: --DEBUG-- show composite sync results
      when: DEBUG and composite_sync_result is defined
      debug:
        msg: "{{ composite_sync_result }}"

    - name: Display synchronization summary
      debug:
        msg:
          - "Template synchronization completed successfully"
          - "Project: {{ projectName }}"
          - "Regular templates synced: {{ template_workflow_configs | default([]) | length }}"
          - "Composite templates synced: {{ composite_workflow_configs | default([]) | length }}"
          - "Timestamp: {{ start_timestamp.date + ' ' + start_timestamp.time }}"
